### ISSUE TITLE
PNG Output

### ISSUE THREAD

**Issue by koutsie** [kylewelsby/now-playing-widget#1]
How about making this render an image version of the now playing too?

**Comment by kylewelsby** [comment]
You mean, to save the output as a static PNG instead of an HTML web page?

**Comment by koutsie** [comment]
Yep!

**Comment by kylewelsby** [comment]
Do you have any proposals about how I am to do that without a server?

Whats wrong with the HTML output?

**Comment by koutsie** [comment]
lmao i found something but idk
https://www.geeksforgeeks.org/how-to-convert-an-html-element-or-document-into-image/
kekw

**Comment by kylewelsby** [comment]
Could you give me more information about why image output is more important than HTML?

**Comment by koutsie** [comment]
alignment mainly.

**Comment by kylewelsby** [comment]
You can resize the browser output in OBS and retain great resolution quality. 

I can't see any benefit for the added complexity to render out a rendered image. 

I'm going to close this for now until there's some solid evidence of what feature this would bring.
